// Auto-generated by `npm run supabase:types`.
// Do not edit manually.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      brands: {
        Row: {
          created_at: string
          id: string
          image_url: string | null
          name: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          image_url?: string | null
          name?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          image_url?: string | null
          name?: string | null
        }
        Relationships: []
      }
      clinic_memberships: {
        Row: {
          clinic_id: string
          created_at: string
          id: string
          role: string | null
          user_id: string
        }
        Insert: {
          clinic_id: string
          created_at?: string
          id?: string
          role?: string | null
          user_id: string
        }
        Update: {
          clinic_id?: string
          created_at?: string
          id?: string
          role?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinic_memberships_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "clinic_memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      clinics: {
        Row: {
          created_at: string | null
          created_by: string | null
          id: string
          location_address: Json | null
          name: string
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          id?: string
          location_address?: Json | null
          name: string
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          id?: string
          location_address?: Json | null
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinics_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_items: {
        Row: {
          batch_number: string | null
          clinic_id: string
          expiry_date: string | null
          hibc_secondary: string | null
          id: string
          last_updated: string | null
          location: string | null
          price: number | null
          product_id: string
          quantity: number
          udi_pi: string | null
          VAT: number | null
        }
        Insert: {
          batch_number?: string | null
          clinic_id: string
          expiry_date?: string | null
          hibc_secondary?: string | null
          id?: string
          last_updated?: string | null
          location?: string | null
          price?: number | null
          product_id: string
          quantity?: number
          udi_pi?: string | null
          VAT?: number | null
        }
        Update: {
          batch_number?: string | null
          clinic_id?: string
          expiry_date?: string | null
          hibc_secondary?: string | null
          id?: string
          last_updated?: string | null
          location?: string | null
          price?: number | null
          product_id?: string
          quantity?: number
          udi_pi?: string | null
          VAT?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "inventory_items_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      manufacturers: {
        Row: {
          created_at: string | null
          fiscal_code: string | null
          full_legal_name: string | null
          gs1_prefix: string | null
          hibc_lic: string | null
          id: string
          legal_name_norm: string | null
          metadata: Json | null
          srn_code: string | null
          VAT: string | null
        }
        Insert: {
          created_at?: string | null
          fiscal_code?: string | null
          full_legal_name?: string | null
          gs1_prefix?: string | null
          hibc_lic?: string | null
          id?: string
          legal_name_norm?: string | null
          metadata?: Json | null
          srn_code?: string | null
          VAT?: string | null
        }
        Update: {
          created_at?: string | null
          fiscal_code?: string | null
          full_legal_name?: string | null
          gs1_prefix?: string | null
          hibc_lic?: string | null
          id?: string
          legal_name_norm?: string | null
          metadata?: Json | null
          srn_code?: string | null
          VAT?: string | null
        }
        Relationships: []
      }
      master_catalog: {
        Row: {
          brand_id: string | null
          created_at: string | null
          default_description: string | null
          default_min_stock: number | null
          ean: string | null
          hibc_primary: string | null
          id: string
          image_url: string | null
          manufacturer_id: string | null
          metadata: Json | null
          name: string
          search_payload: string | null
          sku: string | null
          tags: string[] | null
          udi_di: string | null
        }
        Insert: {
          brand_id?: string | null
          created_at?: string | null
          default_description?: string | null
          default_min_stock?: number | null
          ean?: string | null
          hibc_primary?: string | null
          id?: string
          image_url?: string | null
          manufacturer_id?: string | null
          metadata?: Json | null
          name: string
          search_payload?: string | null
          sku?: string | null
          tags?: string[] | null
          udi_di?: string | null
        }
        Update: {
          brand_id?: string | null
          created_at?: string | null
          default_description?: string | null
          default_min_stock?: number | null
          ean?: string | null
          hibc_primary?: string | null
          id?: string
          image_url?: string | null
          manufacturer_id?: string | null
          metadata?: Json | null
          name?: string
          search_payload?: string | null
          sku?: string | null
          tags?: string[] | null
          udi_di?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "master_catalog_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "master_catalog_manufacturer_id_fkey"
            columns: ["manufacturer_id"]
            isOneToOne: false
            referencedRelation: "manufacturers"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          brand_id: string | null
          category: string | null
          clinic_id: string
          created_at: string | null
          description: string | null
          ean: string | null
          hibc_primary: string | null
          id: string
          image_url: string | null
          master_catalogue_id: string | null
          metadata: Json | null
          min_stock_level: number | null
          name: string
          sku: string | null
          supplier_id: string | null
          udi_di: string | null
        }
        Insert: {
          brand_id?: string | null
          category?: string | null
          clinic_id: string
          created_at?: string | null
          description?: string | null
          ean?: string | null
          hibc_primary?: string | null
          id?: string
          image_url?: string | null
          master_catalogue_id?: string | null
          metadata?: Json | null
          min_stock_level?: number | null
          name: string
          sku?: string | null
          supplier_id?: string | null
          udi_di?: string | null
        }
        Update: {
          brand_id?: string | null
          category?: string | null
          clinic_id?: string
          created_at?: string | null
          description?: string | null
          ean?: string | null
          hibc_primary?: string | null
          id?: string
          image_url?: string | null
          master_catalogue_id?: string | null
          metadata?: Json | null
          min_stock_level?: number | null
          name?: string
          sku?: string | null
          supplier_id?: string | null
          udi_di?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "products_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_master_catalogue_id_fkey"
            columns: ["master_catalogue_id"]
            isOneToOne: false
            referencedRelation: "master_catalog"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string | null
          full_name: string | null
          id: string
          role: string | null
        }
        Insert: {
          created_at?: string | null
          full_name?: string | null
          id: string
          role?: string | null
        }
        Update: {
          created_at?: string | null
          full_name?: string | null
          id?: string
          role?: string | null
        }
        Relationships: []
      }
      stock_movements: {
        Row: {
          clinic_id: string
          created_at: string | null
          id: string
          internal_meta: Json | null
          inventory_item_id: string | null
          movement_type: string | null
          notes: string | null
          product_id: string
          quantity: number
        }
        Insert: {
          clinic_id: string
          created_at?: string | null
          id?: string
          internal_meta?: Json | null
          inventory_item_id?: string | null
          movement_type?: string | null
          notes?: string | null
          product_id: string
          quantity: number
        }
        Update: {
          clinic_id?: string
          created_at?: string | null
          id?: string
          internal_meta?: Json | null
          inventory_item_id?: string | null
          movement_type?: string | null
          notes?: string | null
          product_id?: string
          quantity?: number
        }
        Relationships: [
          {
            foreignKeyName: "stock_movements_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_movements_inventory_item_id_fkey"
            columns: ["inventory_item_id"]
            isOneToOne: false
            referencedRelation: "inventory_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_movements_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      suppliers: {
        Row: {
          clinic_id: string
          contact_person: string | null
          created_at: string | null
          email: string | null
          id: string
          name: string
          phone: string | null
        }
        Insert: {
          clinic_id: string
          contact_person?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          name: string
          phone?: string | null
        }
        Update: {
          clinic_id?: string
          contact_person?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          name?: string
          phone?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "suppliers_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
        ]
      }
      user_active_clinic: {
        Row: {
          clinic_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          clinic_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          clinic_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_active_clinic_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_active_clinic_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      inventory_location_suggestions: {
        Row: {
          clinic_id: string | null
          frequency: number | null
          location: string | null
        }
        Relationships: [
          {
            foreignKeyName: "inventory_items_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
        ]
      }
      view_low_stock: {
        Row: {
          clinic_id: string | null
          min_stock_level: number | null
          name: string | null
          sku: string | null
          total_quantity: number | null
        }
        Relationships: [
          {
            foreignKeyName: "products_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      apply_carico_bulk: {
        Args: { p_clinic_id: string; p_items: Json }
        Returns: Json
      }
      apply_inventario_bulk: {
        Args: { p_clinic_id: string; p_items: Json }
        Returns: Json
      }
      apply_scarico_bulk: {
        Args: { p_clinic_id: string; p_items: Json }
        Returns: Json
      }
      create_clinic_and_assign: {
        Args: { clinic_address_text?: string; clinic_name: string }
        Returns: string
      }
      get_my_clinic_id: { Args: never; Returns: string }
      get_my_clinics: {
        Args: never
        Returns: {
          clinic_id: string
          clinic_name: string
          is_current: boolean
          joined_at: string
          location_address: Json
          role: string
        }[]
      }
      immutable_unaccent: { Args: { val: string }; Returns: string }
      master_catalog_compute_search_tsv: {
        Args: {
          p_brand_name: string
          p_default_description: string
          p_ean: string
          p_hibc_primary: string
          p_name: string
          p_sku: string
          p_tags: string[]
          p_udi_di: string
        }
        Returns: unknown
      }
      normalize_inventory_location: { Args: { p_raw: string }; Returns: string }
      search_inventory_locations: {
        Args: { p_clinic_id: string; p_limit?: number; p_prefix?: string }
        Returns: {
          frequency: number
          location: string
        }[]
      }
      search_master_catalog: {
        Args: {
          page_limit?: number
          page_offset?: number
          search_text?: string
          target_clinic_id?: string
        }
        Returns: {
          brand: string
          brand_image_url: string
          default_min_stock: number
          ean: string
          id: string
          image_url: string
          manufacturer: string | null
          name: string
          sku: string
          tags: string[]
        }[]
      }
      set_my_active_clinic: {
        Args: { target_clinic_id: string }
        Returns: string
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
      unaccent: { Args: { "": string }; Returns: string }
      update_my_clinic: {
        Args: {
          clinic_address_text?: string
          clinic_name: string
          target_clinic_id: string
        }
        Returns: string
      }
      upsert_manufacturers_rdm_batch: {
        Args: { p_rows: Json }
        Returns: number
      }
      upsert_master_catalog_rdm_batch: {
        Args: { p_rows: Json }
        Returns: number
      }
      upsert_master_catalog_rdm_batch_insert_only: {
        Args: { p_rows: Json }
        Returns: number
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
